[project]
name = "bayessdf"
version = "0.1"

dependencies=[
    "torchtyping>=0.1.4"
]

[tool.setuptools]
packages = ["bayessdf"]

[project.entry-points.'nerfstudio.dataparser_configs']
nb-dataparser = 'bayessdf.dataparsers.nerfbusters.nerfbuster_config:nbDataparser'
sparse-nerfstudio = 'bayessdf.dataparsers.sparse.sparse_nerfstudio_config:sparseNsDataparser'

[project.scripts]
# Note, add entrypoint name to nerfstudio/scripts/completions/install.py to include CLI completion
ns-uncertainty = "bayessdf.scripts.uncertainty:entrypoint"
ns-render-u = "bayessdf.scripts.render_uncertainty:entrypoint"
ns-viewer-u = "bayessdf.scripts.viewer_uncertainty.run_viewer_u:entrypoint"
ns-eval-u = "bayessdf.scripts.eval_uncertainty:entrypoint"

